(define (and? exp) (tagged-list? exp 'and))
(define (or? exp) (tagged-list? exp 'or))
(define (and-predicates exp) (cdr exp))
(define (or-predicates exp) (cdr exp))
(define (first-predicate seq) (car seq))
(define (rest-predicates seq) (cdr seq))

(define (eval-and exps env)
  (define (go exps last-result)
    (if (null? exps)
      last-result
      (let ((value (eval (first-predicate exps) env)))
        (if (not (true? value))
          'false
          (go (rest-predicate exps) value)))))
  (go exps 'true))

(define (eval-or exps env)
  (if (null? exps)
    'false
    (let ((value (eval (first-predicate exps) env)))
      (if (true? value)
        value
        (eval-or (rest-predicate exps) env)))))

(define (eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((quoted? exp) (text-of-quotation exp))
        ((assignment? exp) (eval-assignment exp env))
        ((definition? exp) (eval-definition exp env))
        ((if? exp) (eval-if exp env))
        ((lambda? exp)
         (make-procedure (lambda-parameters exp)
                         (lambda-body exp)
                         env))
        ((begin? exp)
         (eval-sequence (begin-actions exp) env))
        ((cond? exp) (eval (cond->if exp) env))
        ((and? exp) (eval-and (and-predicates exp) env))
        ((or? exp) (eval-or (or-predicates exp) env))
        ((application? exp)
         (apply (eval (operator exp) env)
                (list-of-values (operands exp) env)))
        (else
          (error "Unknown expression type -- EVAL" exp))))
