(define (make-account balance passwd)
  (define (incorrect? pw)
    (not (eq? pw passwd)))
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (if (incorrect? pw)
      (lambda x "Incorrect password")
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m)))))
  dispatch)

(define acc (make-account 100 'secret-password))

(define (main args)
  (print ((acc 'secret-password 'withdraw) 40))
  (print ((acc 'secret-password 'deposit) 50))
  (print ((acc 'some-other-password 'deposit) 50))
  (print ((acc 'secret-password 'deposit) 50)))
